// transcoder.proto is the wire contract between the main open-streamer
// process and a per-stream open-streamer-transcoder subprocess.
//
// One Unix-domain socket per stream. The supervisor in
// internal/transcoder/service.go opens a bidi stream and pushes raw
// ingest TS bytes + control messages; the subprocess returns encoded
// MPEG-TS chunks per rendition + health / error events.
//
// Single bidi stream (not unary RPCs) so a missed packet on the wire
// kills the stream and the supervisor respawns the subprocess — keeps
// failure semantics identical to crash recovery.
//
// P0 SCOPE: contract sketch only. Code generation (protoc → .pb.go) is
// deferred to P4 when the gRPC supervisor lands. Until then the file
// documents the intended wire layout for review.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: transcoder.proto

package transcoderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HWBackend int32

const (
	HWBackend_HW_BACKEND_UNSPECIFIED  HWBackend = 0
	HWBackend_HW_BACKEND_CPU          HWBackend = 1 // libx264 / libx265
	HWBackend_HW_BACKEND_NVENC        HWBackend = 2 // NVIDIA
	HWBackend_HW_BACKEND_VAAPI        HWBackend = 3 // Intel / AMD on Linux
	HWBackend_HW_BACKEND_VIDEOTOOLBOX HWBackend = 4 // macOS
	HWBackend_HW_BACKEND_QSV          HWBackend = 5 // Intel Quick Sync
)

// Enum value maps for HWBackend.
var (
	HWBackend_name = map[int32]string{
		0: "HW_BACKEND_UNSPECIFIED",
		1: "HW_BACKEND_CPU",
		2: "HW_BACKEND_NVENC",
		3: "HW_BACKEND_VAAPI",
		4: "HW_BACKEND_VIDEOTOOLBOX",
		5: "HW_BACKEND_QSV",
	}
	HWBackend_value = map[string]int32{
		"HW_BACKEND_UNSPECIFIED":  0,
		"HW_BACKEND_CPU":          1,
		"HW_BACKEND_NVENC":        2,
		"HW_BACKEND_VAAPI":        3,
		"HW_BACKEND_VIDEOTOOLBOX": 4,
		"HW_BACKEND_QSV":          5,
	}
)

func (x HWBackend) Enum() *HWBackend {
	p := new(HWBackend)
	*p = x
	return p
}

func (x HWBackend) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HWBackend) Descriptor() protoreflect.EnumDescriptor {
	return file_transcoder_proto_enumTypes[0].Descriptor()
}

func (HWBackend) Type() protoreflect.EnumType {
	return &file_transcoder_proto_enumTypes[0]
}

func (x HWBackend) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HWBackend.Descriptor instead.
func (HWBackend) EnumDescriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{0}
}

// Codec identifies the elementary-stream type of an OutputPacket so the
// supervisor can build domain.AVPacket without inspecting bytes.
//
// CODEC_UNSPECIFIED keeps the field zero-value safe: an older subprocess
// (or any bug that leaves codec unset) surfaces as a clear "unknown
// codec" error in the supervisor rather than silently misrouted into
// the H.264 path.
type Codec int32

const (
	Codec_CODEC_UNSPECIFIED Codec = 0
	Codec_CODEC_H264        Codec = 1
	Codec_CODEC_H265        Codec = 2
	Codec_CODEC_AAC         Codec = 3
)

// Enum value maps for Codec.
var (
	Codec_name = map[int32]string{
		0: "CODEC_UNSPECIFIED",
		1: "CODEC_H264",
		2: "CODEC_H265",
		3: "CODEC_AAC",
	}
	Codec_value = map[string]int32{
		"CODEC_UNSPECIFIED": 0,
		"CODEC_H264":        1,
		"CODEC_H265":        2,
		"CODEC_AAC":         3,
	}
)

func (x Codec) Enum() *Codec {
	p := new(Codec)
	*p = x
	return p
}

func (x Codec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Codec) Descriptor() protoreflect.EnumDescriptor {
	return file_transcoder_proto_enumTypes[1].Descriptor()
}

func (Codec) Type() protoreflect.EnumType {
	return &file_transcoder_proto_enumTypes[1]
}

func (x Codec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Codec.Descriptor instead.
func (Codec) EnumDescriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{1}
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Request_Configure
	//	*Request_Packet
	//	*Request_Switch
	//	*Request_Stop
	Body          isRequest_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_transcoder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetBody() isRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Request) GetConfigure() *ConfigureRequest {
	if x != nil {
		if x, ok := x.Body.(*Request_Configure); ok {
			return x.Configure
		}
	}
	return nil
}

func (x *Request) GetPacket() *InputPacket {
	if x != nil {
		if x, ok := x.Body.(*Request_Packet); ok {
			return x.Packet
		}
	}
	return nil
}

func (x *Request) GetSwitch() *SwitchInput {
	if x != nil {
		if x, ok := x.Body.(*Request_Switch); ok {
			return x.Switch
		}
	}
	return nil
}

func (x *Request) GetStop() *Stop {
	if x != nil {
		if x, ok := x.Body.(*Request_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

type isRequest_Body interface {
	isRequest_Body()
}

type Request_Configure struct {
	Configure *ConfigureRequest `protobuf:"bytes,1,opt,name=configure,proto3,oneof"`
}

type Request_Packet struct {
	Packet *InputPacket `protobuf:"bytes,2,opt,name=packet,proto3,oneof"`
}

type Request_Switch struct {
	Switch *SwitchInput `protobuf:"bytes,3,opt,name=switch,proto3,oneof"`
}

type Request_Stop struct {
	Stop *Stop `protobuf:"bytes,4,opt,name=stop,proto3,oneof"`
}

func (*Request_Configure) isRequest_Body() {}

func (*Request_Packet) isRequest_Body() {}

func (*Request_Switch) isRequest_Body() {}

func (*Request_Stop) isRequest_Body() {}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Event_Packet
	//	*Event_Health
	//	*Event_Error
	Body          isEvent_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_transcoder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetBody() isEvent_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Event) GetPacket() *OutputPacket {
	if x != nil {
		if x, ok := x.Body.(*Event_Packet); ok {
			return x.Packet
		}
	}
	return nil
}

func (x *Event) GetHealth() *Health {
	if x != nil {
		if x, ok := x.Body.(*Event_Health); ok {
			return x.Health
		}
	}
	return nil
}

func (x *Event) GetError() *Error {
	if x != nil {
		if x, ok := x.Body.(*Event_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isEvent_Body interface {
	isEvent_Body()
}

type Event_Packet struct {
	Packet *OutputPacket `protobuf:"bytes,1,opt,name=packet,proto3,oneof"`
}

type Event_Health struct {
	Health *Health `protobuf:"bytes,2,opt,name=health,proto3,oneof"`
}

type Event_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*Event_Packet) isEvent_Body() {}

func (*Event_Health) isEvent_Body() {}

func (*Event_Error) isEvent_Body() {}

type ConfigureRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StreamCode     string                 `protobuf:"bytes,1,opt,name=stream_code,json=streamCode,proto3" json:"stream_code,omitempty"`
	RawIngestBufId string                 `protobuf:"bytes,2,opt,name=raw_ingest_buf_id,json=rawIngestBufId,proto3" json:"raw_ingest_buf_id,omitempty"`
	HwBackend      HWBackend              `protobuf:"varint,3,opt,name=hw_backend,json=hwBackend,proto3,enum=transcoder.v1.HWBackend" json:"hw_backend,omitempty"`
	Targets        []*Target              `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
	Audio          *AudioConfig           `protobuf:"bytes,5,opt,name=audio,proto3" json:"audio,omitempty"`
	Watermark      *WatermarkConfig       `protobuf:"bytes,6,opt,name=watermark,proto3" json:"watermark,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_transcoder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigureRequest) GetStreamCode() string {
	if x != nil {
		return x.StreamCode
	}
	return ""
}

func (x *ConfigureRequest) GetRawIngestBufId() string {
	if x != nil {
		return x.RawIngestBufId
	}
	return ""
}

func (x *ConfigureRequest) GetHwBackend() HWBackend {
	if x != nil {
		return x.HwBackend
	}
	return HWBackend_HW_BACKEND_UNSPECIFIED
}

func (x *ConfigureRequest) GetTargets() []*Target {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *ConfigureRequest) GetAudio() *AudioConfig {
	if x != nil {
		return x.Audio
	}
	return nil
}

func (x *ConfigureRequest) GetWatermark() *WatermarkConfig {
	if x != nil {
		return x.Watermark
	}
	return nil
}

type Target struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OutputBufId    string                 `protobuf:"bytes,1,opt,name=output_buf_id,json=outputBufId,proto3" json:"output_buf_id,omitempty"`
	Index          int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Width          int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height         int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	BitrateKbps    int32                  `protobuf:"varint,5,opt,name=bitrate_kbps,json=bitrateKbps,proto3" json:"bitrate_kbps,omitempty"`
	MaxBitrateKbps int32                  `protobuf:"varint,6,opt,name=max_bitrate_kbps,json=maxBitrateKbps,proto3" json:"max_bitrate_kbps,omitempty"`
	Framerate      float64                `protobuf:"fixed64,7,opt,name=framerate,proto3" json:"framerate,omitempty"`
	// gop_seconds is the legacy per-profile keyframe interval (seconds).
	// Honoured only when gop_frames == 0 — frame-count is preferred
	// because seconds-to-frames conversion at the subprocess loses
	// precision when the configured GOP isn't an integer multiple of
	// the framerate.
	GopSeconds int32  `protobuf:"varint,8,opt,name=gop_seconds,json=gopSeconds,proto3" json:"gop_seconds,omitempty"`
	Codec      string `protobuf:"bytes,9,opt,name=codec,proto3" json:"codec,omitempty"`
	Preset     string `protobuf:"bytes,10,opt,name=preset,proto3" json:"preset,omitempty"`
	Profile    string `protobuf:"bytes,11,opt,name=profile,proto3" json:"profile,omitempty"`
	Level      string `protobuf:"bytes,12,opt,name=level,proto3" json:"level,omitempty"`
	// Bframes and refs use sentinel -1 for "encoder default" because
	// proto3 cannot distinguish absent int32 from zero.
	BframesOrNeg1 int32  `protobuf:"varint,13,opt,name=bframes_or_neg1,json=bframesOrNeg1,proto3" json:"bframes_or_neg1,omitempty"`
	RefsOrNeg1    int32  `protobuf:"varint,14,opt,name=refs_or_neg1,json=refsOrNeg1,proto3" json:"refs_or_neg1,omitempty"`
	Sar           string `protobuf:"bytes,15,opt,name=sar,proto3" json:"sar,omitempty"`
	ResizeMode    string `protobuf:"bytes,16,opt,name=resize_mode,json=resizeMode,proto3" json:"resize_mode,omitempty"`
	// gop_frames is the preferred keyframe interval expressed in
	// frames (encoder's native unit). The supervisor resolves
	// profile.KeyframeInterval (seconds) and TranscoderGlobalConfig.GOP
	// (frames) into this single field so the subprocess does no math.
	// Zero = encoder default.
	GopFrames     int32 `protobuf:"varint,17,opt,name=gop_frames,json=gopFrames,proto3" json:"gop_frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_transcoder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{3}
}

func (x *Target) GetOutputBufId() string {
	if x != nil {
		return x.OutputBufId
	}
	return ""
}

func (x *Target) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Target) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Target) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Target) GetBitrateKbps() int32 {
	if x != nil {
		return x.BitrateKbps
	}
	return 0
}

func (x *Target) GetMaxBitrateKbps() int32 {
	if x != nil {
		return x.MaxBitrateKbps
	}
	return 0
}

func (x *Target) GetFramerate() float64 {
	if x != nil {
		return x.Framerate
	}
	return 0
}

func (x *Target) GetGopSeconds() int32 {
	if x != nil {
		return x.GopSeconds
	}
	return 0
}

func (x *Target) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *Target) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *Target) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *Target) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Target) GetBframesOrNeg1() int32 {
	if x != nil {
		return x.BframesOrNeg1
	}
	return 0
}

func (x *Target) GetRefsOrNeg1() int32 {
	if x != nil {
		return x.RefsOrNeg1
	}
	return 0
}

func (x *Target) GetSar() string {
	if x != nil {
		return x.Sar
	}
	return ""
}

func (x *Target) GetResizeMode() string {
	if x != nil {
		return x.ResizeMode
	}
	return ""
}

func (x *Target) GetGopFrames() int32 {
	if x != nil {
		return x.GopFrames
	}
	return 0
}

type AudioConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Copy          bool                   `protobuf:"varint,1,opt,name=copy,proto3" json:"copy,omitempty"`
	Codec         string                 `protobuf:"bytes,2,opt,name=codec,proto3" json:"codec,omitempty"`
	BitrateK      int32                  `protobuf:"varint,3,opt,name=bitrate_k,json=bitrateK,proto3" json:"bitrate_k,omitempty"`
	SampleRate    int32                  `protobuf:"varint,4,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Channels      int32                  `protobuf:"varint,5,opt,name=channels,proto3" json:"channels,omitempty"`
	Normalize     bool                   `protobuf:"varint,6,opt,name=normalize,proto3" json:"normalize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioConfig) Reset() {
	*x = AudioConfig{}
	mi := &file_transcoder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioConfig) ProtoMessage() {}

func (x *AudioConfig) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioConfig.ProtoReflect.Descriptor instead.
func (*AudioConfig) Descriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{4}
}

func (x *AudioConfig) GetCopy() bool {
	if x != nil {
		return x.Copy
	}
	return false
}

func (x *AudioConfig) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *AudioConfig) GetBitrateK() int32 {
	if x != nil {
		return x.BitrateK
	}
	return 0
}

func (x *AudioConfig) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *AudioConfig) GetChannels() int32 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *AudioConfig) GetNormalize() bool {
	if x != nil {
		return x.Normalize
	}
	return false
}

type WatermarkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // "text" | "image"
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	AssetPath     string                 `protobuf:"bytes,4,opt,name=asset_path,json=assetPath,proto3" json:"asset_path,omitempty"`
	Position      string                 `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`
	OffsetX       int32                  `protobuf:"varint,6,opt,name=offset_x,json=offsetX,proto3" json:"offset_x,omitempty"`
	OffsetY       int32                  `protobuf:"varint,7,opt,name=offset_y,json=offsetY,proto3" json:"offset_y,omitempty"`
	Opacity       float64                `protobuf:"fixed64,8,opt,name=opacity,proto3" json:"opacity,omitempty"`
	FontSize      int32                  `protobuf:"varint,9,opt,name=font_size,json=fontSize,proto3" json:"font_size,omitempty"`
	FontColor     string                 `protobuf:"bytes,10,opt,name=font_color,json=fontColor,proto3" json:"font_color,omitempty"`
	FontFile      string                 `protobuf:"bytes,11,opt,name=font_file,json=fontFile,proto3" json:"font_file,omitempty"`
	Resize        bool                   `protobuf:"varint,12,opt,name=resize,proto3" json:"resize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatermarkConfig) Reset() {
	*x = WatermarkConfig{}
	mi := &file_transcoder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatermarkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatermarkConfig) ProtoMessage() {}

func (x *WatermarkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatermarkConfig.ProtoReflect.Descriptor instead.
func (*WatermarkConfig) Descriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{5}
}

func (x *WatermarkConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *WatermarkConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WatermarkConfig) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *WatermarkConfig) GetAssetPath() string {
	if x != nil {
		return x.AssetPath
	}
	return ""
}

func (x *WatermarkConfig) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *WatermarkConfig) GetOffsetX() int32 {
	if x != nil {
		return x.OffsetX
	}
	return 0
}

func (x *WatermarkConfig) GetOffsetY() int32 {
	if x != nil {
		return x.OffsetY
	}
	return 0
}

func (x *WatermarkConfig) GetOpacity() float64 {
	if x != nil {
		return x.Opacity
	}
	return 0
}

func (x *WatermarkConfig) GetFontSize() int32 {
	if x != nil {
		return x.FontSize
	}
	return 0
}

func (x *WatermarkConfig) GetFontColor() string {
	if x != nil {
		return x.FontColor
	}
	return ""
}

func (x *WatermarkConfig) GetFontFile() string {
	if x != nil {
		return x.FontFile
	}
	return ""
}

func (x *WatermarkConfig) GetResize() bool {
	if x != nil {
		return x.Resize
	}
	return false
}

type InputPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`                                      // raw MPEG-TS bytes from the buffer hub
	SessionStart  bool                   `protobuf:"varint,2,opt,name=session_start,json=sessionStart,proto3" json:"session_start,omitempty"` // mirrors buffer.Packet.SessionStart
	SessionId     int64                  `protobuf:"varint,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputPacket) Reset() {
	*x = InputPacket{}
	mi := &file_transcoder_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputPacket) ProtoMessage() {}

func (x *InputPacket) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputPacket.ProtoReflect.Descriptor instead.
func (*InputPacket) Descriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{6}
}

func (x *InputPacket) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InputPacket) GetSessionStart() bool {
	if x != nil {
		return x.SessionStart
	}
	return false
}

func (x *InputPacket) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type OutputPacket struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	TargetIndex int32                  `protobuf:"varint,1,opt,name=target_index,json=targetIndex,proto3" json:"target_index,omitempty"` // matches Target.index
	Data        []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                   // codec ES bytes (Annex-B for H.264/H.265, raw ADTS for AAC)
	Codec       Codec                  `protobuf:"varint,3,opt,name=codec,proto3,enum=transcoder.v1.Codec" json:"codec,omitempty"`       // identifies the codec for the supervisor's AV-path write
	PtsMs       int64                  `protobuf:"varint,4,opt,name=pts_ms,json=ptsMs,proto3" json:"pts_ms,omitempty"`                   // milliseconds; from encoder for video, demuxer for audio
	DtsMs       int64                  `protobuf:"varint,5,opt,name=dts_ms,json=dtsMs,proto3" json:"dts_ms,omitempty"`                   // milliseconds; equals pts_ms when source has no separate DTS
	Keyframe    bool                   `protobuf:"varint,6,opt,name=keyframe,proto3" json:"keyframe,omitempty"`                          // IDR for H.264/H.265; always false for AAC
	// session_start=true marks the first packet emitted after an
	// input switch so the supervisor sets buffer.Packet.SessionStart
	// and the publisher emits EXT-X-DISCONTINUITY on the next HLS
	// segment. Without that, players keep the old source's MSE init
	// context across the switch and decode the new source's frames
	// (different PTS base, sometimes different framerate) into
	// visible corruption that doesn't recover without a reload.
	SessionStart  bool `protobuf:"varint,7,opt,name=session_start,json=sessionStart,proto3" json:"session_start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputPacket) Reset() {
	*x = OutputPacket{}
	mi := &file_transcoder_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputPacket) ProtoMessage() {}

func (x *OutputPacket) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputPacket.ProtoReflect.Descriptor instead.
func (*OutputPacket) Descriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{7}
}

func (x *OutputPacket) GetTargetIndex() int32 {
	if x != nil {
		return x.TargetIndex
	}
	return 0
}

func (x *OutputPacket) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OutputPacket) GetCodec() Codec {
	if x != nil {
		return x.Codec
	}
	return Codec_CODEC_UNSPECIFIED
}

func (x *OutputPacket) GetPtsMs() int64 {
	if x != nil {
		return x.PtsMs
	}
	return 0
}

func (x *OutputPacket) GetDtsMs() int64 {
	if x != nil {
		return x.DtsMs
	}
	return 0
}

func (x *OutputPacket) GetKeyframe() bool {
	if x != nil {
		return x.Keyframe
	}
	return false
}

func (x *OutputPacket) GetSessionStart() bool {
	if x != nil {
		return x.SessionStart
	}
	return false
}

type SwitchInput struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NewRawIngestBufId string                 `protobuf:"bytes,1,opt,name=new_raw_ingest_buf_id,json=newRawIngestBufId,proto3" json:"new_raw_ingest_buf_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SwitchInput) Reset() {
	*x = SwitchInput{}
	mi := &file_transcoder_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchInput) ProtoMessage() {}

func (x *SwitchInput) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchInput.ProtoReflect.Descriptor instead.
func (*SwitchInput) Descriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{8}
}

func (x *SwitchInput) GetNewRawIngestBufId() string {
	if x != nil {
		return x.NewRawIngestBufId
	}
	return ""
}

type Stop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stop) Reset() {
	*x = Stop{}
	mi := &file_transcoder_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stop) ProtoMessage() {}

func (x *Stop) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stop.ProtoReflect.Descriptor instead.
func (*Stop) Descriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{9}
}

func (x *Stop) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Health struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*Health_Profile      `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Health) Reset() {
	*x = Health{}
	mi := &file_transcoder_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Health) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Health) ProtoMessage() {}

func (x *Health) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Health.ProtoReflect.Descriptor instead.
func (*Health) Descriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{10}
}

func (x *Health) GetProfiles() []*Health_Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TargetIndex   int32                  `protobuf:"varint,2,opt,name=target_index,json=targetIndex,proto3" json:"target_index,omitempty"` // -1 = stream-level
	Terminal      bool                   `protobuf:"varint,3,opt,name=terminal,proto3" json:"terminal,omitempty"`                          // true = subprocess will exit after sending
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_transcoder_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{11}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetTargetIndex() int32 {
	if x != nil {
		return x.TargetIndex
	}
	return 0
}

func (x *Error) GetTerminal() bool {
	if x != nil {
		return x.Terminal
	}
	return false
}

// Cumulative restart counter per profile so the supervisor can mirror
// it into transcoder.RuntimeStatus without state of its own.
type Health_Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	RestartCount  int32                  `protobuf:"varint,2,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	Unhealthy     bool                   `protobuf:"varint,3,opt,name=unhealthy,proto3" json:"unhealthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Health_Profile) Reset() {
	*x = Health_Profile{}
	mi := &file_transcoder_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Health_Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Health_Profile) ProtoMessage() {}

func (x *Health_Profile) ProtoReflect() protoreflect.Message {
	mi := &file_transcoder_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Health_Profile.ProtoReflect.Descriptor instead.
func (*Health_Profile) Descriptor() ([]byte, []int) {
	return file_transcoder_proto_rawDescGZIP(), []int{10, 0}
}

func (x *Health_Profile) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Health_Profile) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *Health_Profile) GetUnhealthy() bool {
	if x != nil {
		return x.Unhealthy
	}
	return false
}

var File_transcoder_proto protoreflect.FileDescriptor

const file_transcoder_proto_rawDesc = "" +
	"\n" +
	"\x10transcoder.proto\x12\rtranscoder.v1\"\xe9\x01\n" +
	"\aRequest\x12?\n" +
	"\tconfigure\x18\x01 \x01(\v2\x1f.transcoder.v1.ConfigureRequestH\x00R\tconfigure\x124\n" +
	"\x06packet\x18\x02 \x01(\v2\x1a.transcoder.v1.InputPacketH\x00R\x06packet\x124\n" +
	"\x06switch\x18\x03 \x01(\v2\x1a.transcoder.v1.SwitchInputH\x00R\x06switch\x12)\n" +
	"\x04stop\x18\x04 \x01(\v2\x13.transcoder.v1.StopH\x00R\x04stopB\x06\n" +
	"\x04body\"\xa5\x01\n" +
	"\x05Event\x125\n" +
	"\x06packet\x18\x01 \x01(\v2\x1b.transcoder.v1.OutputPacketH\x00R\x06packet\x12/\n" +
	"\x06health\x18\x02 \x01(\v2\x15.transcoder.v1.HealthH\x00R\x06health\x12,\n" +
	"\x05error\x18\x03 \x01(\v2\x14.transcoder.v1.ErrorH\x00R\x05errorB\x06\n" +
	"\x04body\"\xb8\x02\n" +
	"\x10ConfigureRequest\x12\x1f\n" +
	"\vstream_code\x18\x01 \x01(\tR\n" +
	"streamCode\x12)\n" +
	"\x11raw_ingest_buf_id\x18\x02 \x01(\tR\x0erawIngestBufId\x127\n" +
	"\n" +
	"hw_backend\x18\x03 \x01(\x0e2\x18.transcoder.v1.HWBackendR\thwBackend\x12/\n" +
	"\atargets\x18\x04 \x03(\v2\x15.transcoder.v1.TargetR\atargets\x120\n" +
	"\x05audio\x18\x05 \x01(\v2\x1a.transcoder.v1.AudioConfigR\x05audio\x12<\n" +
	"\twatermark\x18\x06 \x01(\v2\x1e.transcoder.v1.WatermarkConfigR\twatermark\"\xf6\x03\n" +
	"\x06Target\x12\"\n" +
	"\routput_buf_id\x18\x01 \x01(\tR\voutputBufId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12!\n" +
	"\fbitrate_kbps\x18\x05 \x01(\x05R\vbitrateKbps\x12(\n" +
	"\x10max_bitrate_kbps\x18\x06 \x01(\x05R\x0emaxBitrateKbps\x12\x1c\n" +
	"\tframerate\x18\a \x01(\x01R\tframerate\x12\x1f\n" +
	"\vgop_seconds\x18\b \x01(\x05R\n" +
	"gopSeconds\x12\x14\n" +
	"\x05codec\x18\t \x01(\tR\x05codec\x12\x16\n" +
	"\x06preset\x18\n" +
	" \x01(\tR\x06preset\x12\x18\n" +
	"\aprofile\x18\v \x01(\tR\aprofile\x12\x14\n" +
	"\x05level\x18\f \x01(\tR\x05level\x12&\n" +
	"\x0fbframes_or_neg1\x18\r \x01(\x05R\rbframesOrNeg1\x12 \n" +
	"\frefs_or_neg1\x18\x0e \x01(\x05R\n" +
	"refsOrNeg1\x12\x10\n" +
	"\x03sar\x18\x0f \x01(\tR\x03sar\x12\x1f\n" +
	"\vresize_mode\x18\x10 \x01(\tR\n" +
	"resizeMode\x12\x1d\n" +
	"\n" +
	"gop_frames\x18\x11 \x01(\x05R\tgopFrames\"\xaf\x01\n" +
	"\vAudioConfig\x12\x12\n" +
	"\x04copy\x18\x01 \x01(\bR\x04copy\x12\x14\n" +
	"\x05codec\x18\x02 \x01(\tR\x05codec\x12\x1b\n" +
	"\tbitrate_k\x18\x03 \x01(\x05R\bbitrateK\x12\x1f\n" +
	"\vsample_rate\x18\x04 \x01(\x05R\n" +
	"sampleRate\x12\x1a\n" +
	"\bchannels\x18\x05 \x01(\x05R\bchannels\x12\x1c\n" +
	"\tnormalize\x18\x06 \x01(\bR\tnormalize\"\xcf\x02\n" +
	"\x0fWatermarkConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"asset_path\x18\x04 \x01(\tR\tassetPath\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\tR\bposition\x12\x19\n" +
	"\boffset_x\x18\x06 \x01(\x05R\aoffsetX\x12\x19\n" +
	"\boffset_y\x18\a \x01(\x05R\aoffsetY\x12\x18\n" +
	"\aopacity\x18\b \x01(\x01R\aopacity\x12\x1b\n" +
	"\tfont_size\x18\t \x01(\x05R\bfontSize\x12\x1d\n" +
	"\n" +
	"font_color\x18\n" +
	" \x01(\tR\tfontColor\x12\x1b\n" +
	"\tfont_file\x18\v \x01(\tR\bfontFile\x12\x16\n" +
	"\x06resize\x18\f \x01(\bR\x06resize\"e\n" +
	"\vInputPacket\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12#\n" +
	"\rsession_start\x18\x02 \x01(\bR\fsessionStart\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\x03R\tsessionId\"\xe0\x01\n" +
	"\fOutputPacket\x12!\n" +
	"\ftarget_index\x18\x01 \x01(\x05R\vtargetIndex\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12*\n" +
	"\x05codec\x18\x03 \x01(\x0e2\x14.transcoder.v1.CodecR\x05codec\x12\x15\n" +
	"\x06pts_ms\x18\x04 \x01(\x03R\x05ptsMs\x12\x15\n" +
	"\x06dts_ms\x18\x05 \x01(\x03R\x05dtsMs\x12\x1a\n" +
	"\bkeyframe\x18\x06 \x01(\bR\bkeyframe\x12#\n" +
	"\rsession_start\x18\a \x01(\bR\fsessionStart\"?\n" +
	"\vSwitchInput\x120\n" +
	"\x15new_raw_ingest_buf_id\x18\x01 \x01(\tR\x11newRawIngestBufId\"\x1e\n" +
	"\x04Stop\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xa7\x01\n" +
	"\x06Health\x129\n" +
	"\bprofiles\x18\x01 \x03(\v2\x1d.transcoder.v1.Health.ProfileR\bprofiles\x1ab\n" +
	"\aProfile\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12#\n" +
	"\rrestart_count\x18\x02 \x01(\x05R\frestartCount\x12\x1c\n" +
	"\tunhealthy\x18\x03 \x01(\bR\tunhealthy\"`\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12!\n" +
	"\ftarget_index\x18\x02 \x01(\x05R\vtargetIndex\x12\x1a\n" +
	"\bterminal\x18\x03 \x01(\bR\bterminal*\x98\x01\n" +
	"\tHWBackend\x12\x1a\n" +
	"\x16HW_BACKEND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eHW_BACKEND_CPU\x10\x01\x12\x14\n" +
	"\x10HW_BACKEND_NVENC\x10\x02\x12\x14\n" +
	"\x10HW_BACKEND_VAAPI\x10\x03\x12\x1b\n" +
	"\x17HW_BACKEND_VIDEOTOOLBOX\x10\x04\x12\x12\n" +
	"\x0eHW_BACKEND_QSV\x10\x05*M\n" +
	"\x05Codec\x12\x15\n" +
	"\x11CODEC_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"CODEC_H264\x10\x01\x12\x0e\n" +
	"\n" +
	"CODEC_H265\x10\x02\x12\r\n" +
	"\tCODEC_AAC\x10\x032E\n" +
	"\n" +
	"Transcoder\x127\n" +
	"\x03Run\x12\x16.transcoder.v1.Request\x1a\x14.transcoder.v1.Event(\x010\x01BVZTgithub.com/ntt0601zcoder/open-streamer/internal/transcoder/native/proto;transcoderpbb\x06proto3"

var (
	file_transcoder_proto_rawDescOnce sync.Once
	file_transcoder_proto_rawDescData []byte
)

func file_transcoder_proto_rawDescGZIP() []byte {
	file_transcoder_proto_rawDescOnce.Do(func() {
		file_transcoder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transcoder_proto_rawDesc), len(file_transcoder_proto_rawDesc)))
	})
	return file_transcoder_proto_rawDescData
}

var file_transcoder_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_transcoder_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_transcoder_proto_goTypes = []any{
	(HWBackend)(0),           // 0: transcoder.v1.HWBackend
	(Codec)(0),               // 1: transcoder.v1.Codec
	(*Request)(nil),          // 2: transcoder.v1.Request
	(*Event)(nil),            // 3: transcoder.v1.Event
	(*ConfigureRequest)(nil), // 4: transcoder.v1.ConfigureRequest
	(*Target)(nil),           // 5: transcoder.v1.Target
	(*AudioConfig)(nil),      // 6: transcoder.v1.AudioConfig
	(*WatermarkConfig)(nil),  // 7: transcoder.v1.WatermarkConfig
	(*InputPacket)(nil),      // 8: transcoder.v1.InputPacket
	(*OutputPacket)(nil),     // 9: transcoder.v1.OutputPacket
	(*SwitchInput)(nil),      // 10: transcoder.v1.SwitchInput
	(*Stop)(nil),             // 11: transcoder.v1.Stop
	(*Health)(nil),           // 12: transcoder.v1.Health
	(*Error)(nil),            // 13: transcoder.v1.Error
	(*Health_Profile)(nil),   // 14: transcoder.v1.Health.Profile
}
var file_transcoder_proto_depIdxs = []int32{
	4,  // 0: transcoder.v1.Request.configure:type_name -> transcoder.v1.ConfigureRequest
	8,  // 1: transcoder.v1.Request.packet:type_name -> transcoder.v1.InputPacket
	10, // 2: transcoder.v1.Request.switch:type_name -> transcoder.v1.SwitchInput
	11, // 3: transcoder.v1.Request.stop:type_name -> transcoder.v1.Stop
	9,  // 4: transcoder.v1.Event.packet:type_name -> transcoder.v1.OutputPacket
	12, // 5: transcoder.v1.Event.health:type_name -> transcoder.v1.Health
	13, // 6: transcoder.v1.Event.error:type_name -> transcoder.v1.Error
	0,  // 7: transcoder.v1.ConfigureRequest.hw_backend:type_name -> transcoder.v1.HWBackend
	5,  // 8: transcoder.v1.ConfigureRequest.targets:type_name -> transcoder.v1.Target
	6,  // 9: transcoder.v1.ConfigureRequest.audio:type_name -> transcoder.v1.AudioConfig
	7,  // 10: transcoder.v1.ConfigureRequest.watermark:type_name -> transcoder.v1.WatermarkConfig
	1,  // 11: transcoder.v1.OutputPacket.codec:type_name -> transcoder.v1.Codec
	14, // 12: transcoder.v1.Health.profiles:type_name -> transcoder.v1.Health.Profile
	2,  // 13: transcoder.v1.Transcoder.Run:input_type -> transcoder.v1.Request
	3,  // 14: transcoder.v1.Transcoder.Run:output_type -> transcoder.v1.Event
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_transcoder_proto_init() }
func file_transcoder_proto_init() {
	if File_transcoder_proto != nil {
		return
	}
	file_transcoder_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_Configure)(nil),
		(*Request_Packet)(nil),
		(*Request_Switch)(nil),
		(*Request_Stop)(nil),
	}
	file_transcoder_proto_msgTypes[1].OneofWrappers = []any{
		(*Event_Packet)(nil),
		(*Event_Health)(nil),
		(*Event_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transcoder_proto_rawDesc), len(file_transcoder_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transcoder_proto_goTypes,
		DependencyIndexes: file_transcoder_proto_depIdxs,
		EnumInfos:         file_transcoder_proto_enumTypes,
		MessageInfos:      file_transcoder_proto_msgTypes,
	}.Build()
	File_transcoder_proto = out.File
	file_transcoder_proto_goTypes = nil
	file_transcoder_proto_depIdxs = nil
}
